name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [stable, unstable, development-target]
    container:
      image: ghcr.io/elementary/docker:${{ matrix.version }}

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgee-0.8-dev libgranite-dev libgtk-4-dev libgtksourceview-5-dev libxml2-dev libarchive-dev libmarkdown2-dev libjson-glib-dev libcairo2-dev libvala-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build install

  flatpak:
    name: Flatpak
    runs-on: ${{ matrix.configuration.runs-on }}

    strategy:
      matrix:
        configuration:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8-${{ matrix.configuration.arch }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.4
        with:
          bundle: minder.flatpak
          manifest-path: com.github.phase1geo.minder.yml
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          arch: ${{ matrix.configuration.arch }}
